@startuml
!include ../c4/C4_Context.puml
AddRelTag("dashed", $textColor=$ARROW_FONT_COLOR, $lineColor=$ARROW_COLOR, $lineStyle=DashedLine())


Person(client, "Клиент", "Клиент банка")
Person(branch_employee, "Фронт-офис банка", "Сотрудник отделения")
Person(backoffice_deposit, "Бэк-офис по депозитам", "Менеджер по депозитам")
Person(backoffice_credit, "Бэк-офис по кредитам", "Менеджер по кредитам")
Person(callcenter, "Кол-центр", "Сотрудник кол-центра")

System_Boundary(it, "IT системы банка"){
    System(IB, "Интернет банк")
    System(site, "Сайт")
    System(orders, "Система заявок")
    System(deposits, "Каталог депозитов, хранение excel ставок")
    System(ABS, "АБС", "Автоматизированная банковская система")
    System(SMS, "СМС-шлюз", "Отправка уведомлений клиентам")
    System(CallCRM, "Система кол-центра", "Заведение обращений клиентов")
    SystemQueue(queue, "Брокер сообщений", "AMPQ")
}

Rel(client, site, "Клиент заходит на страницу депозитов сайта")
Rel(site, deposits, "Сайт получает список депозитов с актуальными ставками из каталога депозитов")
Rel(site, orders, "сохраняет заявку в системе заявок")
Rel(orders, queue, "новая заявка без данных", "async", $tags="dashed")
Rel(queue, CallCRM, "новая заявка без данных", "async", $tags="dashed")
Rel(CallCRM, callcenter, "Уведомление о новой заявке без данных")
Rel(deposits, CallCRM, "Получение персональных ставок из каталога депозитов")
Rel(callcenter, client, "Звонок клиенту для получения данных", "offline", $tags="dashed")
Rel(callcenter, orders, "изменяет заявку в системе заявок -данные клиента, итоговый кредит если выбран персональный")


Rel(client, IB, "Клиент заходит на страницу депозитов ИБ, СМС код", "offline", $tags="dashed")
Rel(IB, deposits, "получает список депозитов с актуальными и персональными ставками")
Rel(IB, orders, "сохраняет выбранную заявку")
Rel(orders, SMS, "Код")
Rel(SMS, client, "Код", "async mobile", $tags="dashed")
Rel(IB, orders, "Код SMS введенный клиентом")
Rel(orders, backoffice_deposit, "уведомляет сотрудника депозитного отдела о новой подтвержденной заявке")
Rel(backoffice_deposit, ABS, "подтверждает ставку и открывает депозит")


Rel(backoffice_credit, deposits, "загрузить файл со стаками и финансовыми расчетами")
Rel(deposits, backoffice_deposit, "уведомляет о загрузке файла")

Rel(backoffice_deposit, deposits, "Скачивает файл, обновляет цены на депозиты и персональные депозиты")


Rel_Neighbor(client, branch_employee, "обращается для открытия депозита")
Rel(branch_employee, deposits, "список депозитов с актуальными  и персональными ставками")
Rel(branch_employee, orders, "с выбранном депозитом делает подтвержденную заявку в систему заявок")
@enduml
